### ISSUE TITLE
 configure: error: Need OpenSSL with SHA-256 support

### ISSUE THREAD

**Issue by karolpivo** [frankmorgner/openpace#16]
Hi,

I'm trying to compile OpenPACE on Ubuntu 14.04 64bit. 

Configure throws: "Need OpenSSL with SHA-256 support". I have installed OpenSSL 1.0.2. it does support SHA256 (at least I can generate SHA256 hashes).

Any suggestions how I could workaround this?

Cheers
K

**Comment by frankmorgner** [comment]
I suppose configure suggested to look at config.log for a detailed description, did you? what's the problem there? how can the problem be reproduced?

**Comment by Watergrass** [comment]
I have the same problem as karolpivo. Error message appears as result of ./configure  after "test -x configure || autoreconf --verbose --install" (http://frankmorgner.github.io/openpace/install.html).

In config.log:

configure:12597: checking for EVP_sha256
configure:12617: gcc -o conftest -g -O2   conftest.c -L/usr/local/ssl/lib -lcrypto    >&5
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x15): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x2b): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x35): undefined reference to `dlclose'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x36f): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x450): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x4cf): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x5b0): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x620): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x690): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x6cf): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x773): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x7c1): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x81e): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
configure:12617: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenPACE"
	<...>
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char EVP_sha256 ();
| int
| main ()
| {
| return EVP_sha256 ();
|   ;
|   return 0;
| }
configure:12621: error: Need OpenSSL with SHA-256 support

**Comment by karolpivo** [comment]
Sorry for not getting back.

I get the same entry in the config.log

| /* end confdefs.h.  */
|
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char EVP_sha256 ();
| int
| main ()
| {
| return EVP_sha256 ();
|   ;
|   return 0;
| }
configure:12621: error: Need OpenSSL with SHA-256 support

**Comment by frankmorgner** [comment]
Are you sure that you are linking against the correct Version of openssl? Config.log should show the openssl linker flags right before the code that you pasted...

Am 24. Februar 2015 12:04:28 MEZ, schrieb karolpivo <notifications@github.com>:
>Sorry for not getting back.
>
>I get the same entry in the config.log
>
>| /* end confdefs.h.  */
>|
>| /* Override any GCC internal prototype to avoid an error.
>|    Use char because int might match the return type of a GCC
>|    builtin and then its argument prototype would still apply.  */
>| #ifdef __cplusplus
>| extern "C"
>| #endif
>| char EVP_sha256 ();
>| int
>| main ()
>| {
>| return EVP_sha256 ();
>|   ;
>|   return 0;
>| }
>configure:12621: error: Need OpenSSL with SHA-256 support
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/frankmorgner/openpace/issues/16#issuecomment-75737372

-- 
Frank Morgner

**Comment by karolpivo** [comment]
That was it - wrong version of OpenSSL. It's complied and installed now.  --enable-openssl-install switch for configure sorted the problem. 

Thanks

**Comment by Watergrass** [comment]
>Are you sure that you are linking against the correct Version of openssl?
Yes, I am sure. I installed only OpenSSL 1.0.2 on my machine. Actually, just "./configure"  throws "Required OpenSSL headers not found", and I use "PKG_CONFIG_PATH=/usr/local/ssl/lib/pkgconfig ./configure" and got "Need OpenSSL with SHA-256 support".
 
>Config.log should show the openssl linker flags right before the code that you pasted
This?
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenPACE"
| #define PACKAGE_TARNAME "openpace"
| #define PACKAGE_VERSION "1.0.0"
| #define PACKAGE_STRING "OpenPACE 1.0.0"
| #define PACKAGE_BUGREPORT "https://github.com/frankmorgner/openpace/issues"
| #define PACKAGE_URL "http://frankmorgner.github.io/openpace/"
| #define PACKAGE "openpace"
| #define VERSION "1.0.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_OPENSSL_OBJ_MAC_H 1
| #define HAVE_OPENSSL_BUFFER_H 1
| #define HAVE_OPENSSL_BIO_H 1
| #define HAVE_OPENSSL_ECDH_H 1
| #define HAVE_OPENSSL_DH_H 1
| #define HAVE_OPENSSL_EVP_H 1
| #define HAVE_OPENSSL_CMAC_H 1
| #define HAVE_OPENSSL_SHA_H 1
| #define HAVE_OPENSSL_AES_H 1
| #define HAVE_OPENSSL_DES_H 1
| /* end confdefs.h.  */

Just in case, I also found this in config.log:
configure:12439: checking for CRYPTO
configure:12446: $PKG_CONFIG --exists --print-errors "libcrypto >= 1.0.2"
configure:12449: $? = 0
configure:12463: $PKG_CONFIG --exists --print-errors "libcrypto >= 1.0.2"
configure:12466: $? = 0
configure:12524: result: yes

**Comment by frankmorgner** [comment]
No, before the program it should look something like this:
```
configure:12598: checking for EVP_sha256
configure:12618: gcc -o conftest -g -O0   conftest.c -L/home/fm/.local/lib -lcrypto   >&5
```
Here, `-L/home/fm/.local/lib -lcrypto` are the linker flags found by `pkg-config`

**Comment by frankmorgner** [comment]
Also, as @karolpivo mentioned, you may add `--enable-openssl-install` which lets openpace compile its own (compatible) version of OpenSSL.

**Comment by Watergrass** [comment]
All right, it's working. (I didn't use --enable-openssl-install in the first place, because I had problems even with it on my previous machine, which has several versions of OpenSSL).

Just for the record, I got next log earlier:
configure:12597: checking for EVP_sha256
configure:12617: gcc -o conftest -g -O2   conftest.c -L/usr/local/ssl/lib -lcrypto    >&5
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x15): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x2b): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x35): undefined reference to `dlclose'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x36f): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x450): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x4cf): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x5b0): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x620): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x690): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x6cf): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x773): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x7c1): undefined reference to `dlerror'
/usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x81e): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
configure:12617: $? = 1

**Comment by frankmorgner** [comment]
You could also use `./configure LIBS="-ldl"` to add the missing linker flag

**Comment by frankmorgner** [comment]
or you use `PKG_CONFIG="pkg-config --static"`

**Comment by RushOnline** [comment]
If you want to install openssl for Ubuntu, download source, unpack it and run following commands:

```bash
./config --prefix=/usr/local --openssldir=/usr/local/etc/ssl shared no-idea no-mdc2 no-rc5 no-zlib  enable-tlsext no-ssl2 enable-ec_nistp_64_gcc_128
make && make test && sudo checkinstall --pkgname libssl-dev make install
```

**Comment by neocsbee** [comment]
@karolpivo: Thanks for sharing the solution! Worked for me too..
