### ISSUE TITLE
cvc-create : Can't create a certificate using SecP curve (only Prime works)

### ISSUE THREAD

**Issue by kanter** [frankmorgner/openpace#17]
Follow these steps:
openssl ecparam -out UTATCVCA00001.pem -name secp192k1 –genkey
#rem OK
openssl pkcs8 -topk8 -nocrypt -in UTATCVCA00001.pem -outform DER -out UTATCVCA00001.pkcs8
#rem OK
cvc-create --role=cvca --type=at --chr=UTATCVCA00001 --expires=160210 --issued=150210 --sign-with=UTATCVCA00001.pkcs8 --scheme=ECDSA_SHA_1
#rem No error occured, infinite loop (CTRL+C to exit)

**Comment by frankmorgner** [comment]
cv_cert.c:1053 fails because b_bn (the second coefficient of your curve) is zero. I have no special insight in neither the specific curve nor how OpenSSL handles it. I am relying on OpenSSL when encoding the public key for the curve. This obviously doesn't work. I'd suggest using a different curve. Note that secp192k1 also is not part of the standardized domain parameters defined in BSI TR-03110.

**Comment by kanter** [comment]
Thank you for your fast reply.
I will try with another curves.
Even if BSI TR-03110 and TR-03111 specify the standardized domain parameters to use, issuer states could choose differents one ( != standardized).
