### ISSUE TITLE
Query Regarding decoding of the certificate

### ISSUE THREAD

**Issue by karthic32** [frankmorgner/openpace#22]
Dear Frank,

We have some PKI certificates that needs to be parsed and has some minor tailoring done in the following fields:

1) CAR 
2) CHR
3) CHAT

In the source code shared in C, this is done by the API "d2i_CVC_CERT()" for both CVC_Create and CVC_Print, which needs modifications for the certificate parsing to be right. 
Can you please suggest where is the definition for the above mention API can be found.

If there is a better way to approach this problem, please suggest.

Thanks In Advance
Karthic

**Comment by frankmorgner** [comment]
The complete API is documented here http://frankmorgner.github.io/openpace/_static/doxygen/modules.html

If I understand correctly, your certificate has some modifications that are not conforming to BSI TR-03110 (or the ICAO documents). Could you elaborate the purpose of this?

CHR and CAR are checked here https://github.com/frankmorgner/openpace/blob/master/src/eac_util.c#L540-L565.If you want to modify the interpretation of the CHAT, you need to dive deeper into the code, because it's a more complex ASN.1 structure.

**Comment by karthic32** [comment]
Dear Frank,

Thanks a lot for your time. 

Yes I agree with you that the "is_chr()" functiona call is used to verify the CAR and the CHR via the function call "cvc_get_reference_string()". All these functions actually get called after decoding the given (hex/bin) file(certificate) into the respective fields structure created (CVC_CERT).

My query is that how is the binary file decoded in to the cert body and signature. Here as per the code we use the function call "d2i_CVC_CERT()" to fill the actual fields in the structure created "CVC_CERT".

As we have some fields in the certificate which are constants (fixed length), but as per the PKI structure it is variable, now we need to change that to a constant length. For this change to be implemented we need the function definition of the API "d2i_CVC_CERT".

Can you please guide.

Thanks In Advance,
Karthic

**Comment by frankmorgner** [comment]
Use `CVC_d2i_CVC_CERT` https://github.com/frankmorgner/openpace/blob/master/src/cv_cert.c#L297-L340 which already does additional sanity checks.
