### ISSUE TITLE
Installation process fails to locate install-sh

### ISSUE THREAD

**Issue by dominikheinz** [frankmorgner/openpace#52]
### Expected behaviour
The `make install` step, should install the library as expected.

### Actual behaviour
The `make install` step fails with the following error:

```
...
make[2]: Nothing to be done for 'install-exec-am'.
/usr/bin/install -c -d /usr/local/share/doc/openpace
cd ./docs && find . -type d -exec ./install-sh -c -d "/usr/local/share/doc/openpace/{}" \;
find: ./install-sh: No such file or directory
find: ./install-sh: No such file or directory
find: ./install-sh: No such file or directory
...
```

### Steps to reproduce

1. Setup a docker container as described in #51 
2. Clone and build the library. Run `make-install` afterwards.
3. Observe that the installation process fails, because (from my understanding), the Makefile has trouble locating the install-sh script.

### Logs
The logs showcase the error. Ignore the PWD print statements (I inserted them trying to debug the problem):
[err.log](https://github.com/frankmorgner/openpace/files/7487842/err.log)

**Comment by xavehunter** [comment]
...
make[2]: Nothing to be done for 'install-exec-am'.
/usr/bin/install -c -d /usr/local/share/doc/openpace
cd ./docs && find . -type d -exec ./install-sh -c -d "/usr/local/share/doc/openpace/{}" \;
find: ./install-sh: No such file or directory
find: ./install-sh: No such file or directory
find: ./install-sh: No such file or directory
...

I got the same error and fixed it by changeing the Makefile... the cd into ./docs made this error because ./install-sh isnt there so you have 2 options you copy the install-sh into the docs folder or replace the command in the Makefile with this.

find ./docs -type d -exec $(MKDIR_P) "$(DESTDIR)$(htmldir)/{}" \;
find ./docs -type f -exec $(INSTALL_DATA) "{}" "$(DESTDIR)$(htmldir)/{}" \
