### ISSUE TITLE
OpenPACE build on Windows

### ISSUE THREAD

**Issue by nshah2588** [frankmorgner/openpace#64]
I am trying to compile the OpenPACE on Windows using Linux as described on this link:

https://frankmorgner.github.io/openpace/install.html

Logs are below

https://gist.github.com/nshah2588/6ccd5e11bfda228ddfaf9944beb5bf0d#file-gistfile1-txt

OpenSSL is already installed on my Linux PC.

I am using Ubuntu 20.04 on my end.

Can you please advise what I am missing?

@frankmorgner

**Comment by frankmorgner** [comment]
This last worked with ubuntu 18.04. However, since cross compilation has always been on shaky ground, I switched to actually portable executables in the CI pipeline (which work for all major OSs). If you need a Windows dll, please use the VC build.

(I actually forgot to push the CI update half a year ago, sorry.)

**Comment by frankmorgner** [comment]
the process is now documented and part of the CI process
